// frontend/src/components/layout/Footer.vue
<template>
  <div :class="['asv_footer', index && 'index']">
    <div class="inner">
      <p>&copy; {{ currentYear }} ASV Group &ndash; Všechna práva vyhrazena.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue"

export default defineComponent({
  props: {
    index: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    return {
      currentYear: new Date().getFullYear(),
    }
  },
})
</script>

// packages/frontend/src/components/layout/Footer.tsx
import React from "react"

export type FooterProps = {
  index?: boolean
}

export const Footer: React.FC<FooterProps> = ({ index }) => {
  return (
    <div className={`asv_footer ${index ? "index" : ""}`}>
      <div className="inner">
        <p>
          &copy; {new Date().getFullYear()} ASV Group &ndash; Všechna práva
          vyhrazena.
        </p>
      </div>
    </div>
  )
}

export default Footer
