// packages/frontend/src/components/global/FullscreenFetchError.tsx
import React from "react"
import { Link } from "react-router-dom"
import FullscreenWrapper from "./FullscreenWrapper"

export const FullscreenFetchError: React.FC = () => (
  <FullscreenWrapper>
    <h1 style={{ fontSize: "3rem", color: "#fff" }}>Došlo k chybě.</h1>
    <p style={{ color: "#fff" }}>
      Omlouváme se, ale nepodařilo se nám získat data. Zkuste to prosím později
    </p>

    <div className="mt-4">
      <Link to="/" className="button is-primary is-inverted is-medium">
        Jít domů
      </Link>
    </div>
  </FullscreenWrapper>
)

// frontend/src/components/global/FullscreenFetchError.vue
<template>
  <fullscreen-wrapper>
    <h1 :style="{ fontSize: '3rem', color: '#fff' }">Došlo k chybě.</h1>
    <p :style="{ color: '#fff' }">
      Omlouváme se, ale nepodařilo se nám získat data. Zkuste to prosím později
    </p>

    <div class="mt-4">
      <router-link to="/" class="button is-primary is-inverted is-medium"> Jít domů </router-link>
    </div>
  </fullscreen-wrapper>
</template>

<script lang="ts">
import { defineComponent } from "vue"
import FullscreenWrapper from "./FullscreenWrapper.vue"

export default defineComponent({
  components: {
    FullscreenWrapper,
  },
})
</script>
