// frontend/src/components/layout/Navbar.vue
<template>
  <nav
    :class="['navbar asv_navbar', fixed && 'fixed']"
    role="navigation"
    aria-label="main navigation"
  >
    <div class="container is-fluid">
      <div class="navbar-brand">
        <router-link class="navbar-item" to="/">
          <logo :color="fixed ? 'white' : 'blue'" width="150" height="56" />
        </router-link>

        <a :class="['navbar-burger burger', active && 'is-active']" @click="active = !active">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div :class="['navbar-menu', active && 'is-active']">
        <div class="navbar-end">
          <router-link class="navbar-item" to="/"> Domov </router-link>
          <router-link to="/projects" class="navbar-item"> Projekty </router-link>
          <router-link to="/about" class="navbar-item"> Co děláme </router-link>
          <router-link to="/contact" class="navbar-item"> Kontakt </router-link>
        </div>
      </div>
    </div>
  </nav>
</template>

<script lang="ts">
import { debounce } from "lodash"
import { defineComponent, onMounted, onUnmounted, reactive } from "vue"
import Logo from "../global/Logo.vue"

export default defineComponent({
  components: { Logo },
  setup() {
    const state = reactive({
      fixed: false,
      active: false,
    })

    const handleScroll = debounce(() => (state.fixed = window.scrollY > 100))

    onMounted(() => window.addEventListener("scroll", handleScroll))

    onUnmounted(() => window.removeEventListener("scroll", handleScroll))

    return state
  },
})
</script>

// src/components/layout/Navbar.tsx
import React, { useEffect, useState } from "react"
import Logo, { LogoProps } from "../global/Logo"
import { debounce } from "lodash"
import { Link } from "react-router-dom"

export default () => {
  const [fixed, setFixed] = useState(false)
  const [logoColor, setLogoColor] = useState(
    (fixed ? "secondary" : "primary") as LogoProps["color"]
  )

  const handleScroll = () => setFixed(window.scrollY > 100)

  useEffect(() => {
    setLogoColor(fixed ? "secondary" : "primary")
  }, [fixed])

  useEffect(() => {
    window.addEventListener("scroll", debounce(handleScroll))

    return () => window.removeEventListener("scroll", () => handleScroll)
  })

  //   return (
  //     <div className={`asv_navbar ${fixed ? "fixed" : ""}`}>
  //       <div className="container is-fluid">
  //         <div className="columns">
  //           <div className="column">
  //             <Logo color={logoColor} width="150" height="550" />
  //           </div>
  //           <div className="column">
  //             <div className="navbar">

  //             </div>
  //           </div>
  //         </div>
  //       </div>
  //     </div>
  //   )

  return (
    <nav
      className={`navbar asv_navbar ${fixed ? "fixed" : ""}`}
      role="navigation"
      aria-label="main navigation"
    >
      <div className="container is-fluid">
        <div className="navbar-brand">
          <Link className="navbar-item" to="/">
            <Logo color={logoColor} width="150" height="56" />
          </Link>

          <a role="button" className="navbar-burger burger">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarBasicExample" className="navbar-menu">
          <div className="navbar-end">
            <div className="navbar-item">
              <Link className="navbar-item" to="/what-do-we-do">
                Co děláme
              </Link>
              <a className="navbar-item">Portfolio</a>
              <a className="navbar-item">Kontakt</a>
            </div>
          </div>
        </div>
      </div>
    </nav>
  )
}
