// frontend/src/components/global/Slider.vue
<template>
  <div class="slider">
    <img :src="image.src" />
    <div class="slider--content">
      <div class="slider--feature">
        <h1>{{ image.text }}</h1>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, onUnmounted, reactive } from "vue"

export default defineComponent({
  setup() {
    const images = [
      {
        src: "/",
        text: "Hello",
      },
    ]

    const state = reactive({
      index: 0,
    })

    const image = computed(() => images[state.index])

    const startTimeout = () =>
      setTimeout(() => {
        state.index = state.index !== images.length - 1 ? state.index + 1 : 0
        startTimeout()
      }, 3000)

    const _t = startTimeout()

    onUnmounted(() => clearTimeout(_t))

    return {
      image,
      images,
    }
  },
})
</script>

// src/components/Slider.tsx
import React, { useEffect, useState } from "react"
// @ts-ignore
import { animated, useTransition, config } from "react-spring"

export type Image = {
  src: string
  text: string
}

export type SliderProps = {
  images: Image[]
}

const Slider: React.FC<SliderProps> = ({ images }) => {
  const [image, setImage] = useState(images[0])
  const [index, setIndex] = useState(0)

  //   const imageAnimation

  const changeImage = () => {
    let newIndex = 0

    if (index !== images.length - 1) {
      newIndex = index + 1
    }

    setIndex(newIndex)
  }

  useEffect(() => {
    setImage(images[index])
    setTimeout(changeImage, 3000)
  }, [index])

  const transitions = useTransition(image, (item) => item.src, {
    from: { opacity: 0 },
    enter: { opacity: 1 },
    leave: { opacity: 0 },
    config: config.molasses,
  })

  return (
    <div className="slider">
      {/* <animated.img src={image.src} /> */}
      {transitions.map(({ item, props, key }) => (
        <animated.div
          key={key}
          className="slide-img"
          style={{
            ...props,
            backgroundImage: `url(${item.src})`,
          }}
        />
      ))}
      <div className="slider--content">
        <div className="slider--feature">
          <h1>{image.text}</h1>
        </div>
      </div>
    </div>
  )
}

export default Slider
