// packages/frontend/src/pages/index-sections/Projects.vue
<template>
  <Container>
    <div class="content is-landing-section has-text-centered mb-6">
      <h1>Naše projekty</h1>
    </div>
    <ColumnWrapper v-if="projects">
      <Column
        size="is-one-third"
        v-for="(el, i) in projects.sort(() => 0.5 - Math.random()).slice(0, 3)"
        :key="i"
      >
        <router-link :to="`/project/${el.slug}`">
          <Card :image="{ src: el.mainImage, alt: el.name }" :isProject="true">
            <h1>{{ el.name }}</h1>
          </Card>
        </router-link>
      </Column>
    </ColumnWrapper>
    <div class="content mt-6 has-text-centered">
      <router-link to="/projects" class="button is-primary is-large">
        Všechny naše projekty
      </router-link>
    </div>
  </Container>
</template>

<script lang="ts">
import { defineComponent, reactive } from "vue"
import Project from "../../api/project"
import Column from "../../components/flex/Column.vue"
import ColumnWrapper from "../../components/flex/ColumnWrapper.vue"
import Container from "../../components/flex/Container.vue"
import Card from "../../components/global/Card.vue"

export default defineComponent({
  components: {
    Column,
    ColumnWrapper,
    Container,
    Card,
  },
  setup() {
    const state = reactive({
      projects: null as object[] | null | false,
    })

    const fetch = async () => {
      try {
        const proj = new Project()
        const res = await proj.getProjects()

        state.projects = res.data.data.projects
      } catch (e) {
        console.log(e)
        state.projects = []
      }
    }
    fetch()

    return state
  },
})
</script>

// src/pages/index-sections/Projects.tsx
import React, { useEffect, useState } from "react"
import { Link } from "react-router-dom"
import { Column } from "../../components/flex/Column"
import ColumnWrapper from "../../components/flex/ColumnWrapper"
import { Container } from "../../components/flex/Container"

import mvc from "../../assets/img/projects/mvc.jpg"
import iceland from "../../assets/img/projects/iceland.jpg"
import vl from "../../assets/img/projects/vl.jpg"
import { Card } from "../../components/global/Card"
import Project from "../../api/project"

export const Projects: React.FC = () => {
  const [projects, setProjects] = useState<any[]>([])

  useEffect(() => {
    const fetch = async () => {
      try {
        const proj = new Project()
        const res = await proj.getProjects()

        setProjects(res.data.data.projects)
      } catch (e) {
        console.log(e)
        setProjects([])
      }
    }
    fetch()
  }, [])

  return (
    <Container>
      <div className="content is-landing-section has-text-centered mb-6">
        <h1>Naše projekty</h1>
      </div>
      <ColumnWrapper>
        {projects
          .sort(() => 0.5 - Math.random())
          .slice(0, 3)
          .map((el, key) => (
            <Column size="is-one-third" key={key}>
              <Link to={`/project/${el.slug}`}>
                <Card
                  content={<h1>{el.name}</h1>}
                  image={{ src: el.mainImage, alt: el.name }}
                  isProject={true}
                />
              </Link>
            </Column>
          ))}
      </ColumnWrapper>
      <div className="content mt-6 has-text-centered">
        <Link to="/projects" className="button is-primary is-large">
          Všechny naše projekty
        </Link>
      </div>
    </Container>
  )
}
