// frontend/src/layouts/DefaultLayout.vue
<template>
  <div>
    <navbar :isParallax="false" />
    <div class="page-content">
      <slot />
    </div>
    <Footer />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue"
import Footer from "../components/layout/Footer.vue"
import Navbar from "../components/layout/Navbar.vue"

export default defineComponent({
  components: {
    Footer,
    Navbar,
  },
})
</script>

// src/layouts/DefaultLayout.tsx
import React from "react"
import Footer from "../components/layout/Footer"
import Navbar from "../components/layout/Navbar"

export const DefaultLayout: React.FC = ({ children: View }) => {
  return (
    <>
      <Navbar isParallax={false} />
      <div className="page-content">
        <div className="view">{View}</div>
        <Footer />
      </div>
    </>
  )
}

export default DefaultLayout
