// frontend/src/components/global/Map.vue
<template>
  <iframe
    title="Mapy Google"
    @load="state.mapLoaded = true"
    :style="{ height, width }"
    :src="url"
  ></iframe>
  <div :style="{ position: absolute }" v-if="!state.mapLoaded">
    <HashLoader color="#004987" size="100" />
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive } from "vue"

export default defineComponent({
  setup() {
    const state = reactive({
      mapLoaded: false,
    })

    return {
      state,
    }
  },
})
</script>

// src/components/global/Map.tsx
import React, { useState } from "react"
import { HashLoader } from "react-spinners"

export type MapProps = {
  url: string
  height: string
  width: string
}

export const Map: React.FC<MapProps> = ({ url, height, width }) => {
  const [mapLoaded, setMapLoaded] = useState(false)

  return (
    <>
      <iframe
        title="Mapy Google"
        onLoad={() => setMapLoaded(true)}
        style={{ height, width }}
        src={url}
      ></iframe>
      {!mapLoaded && (
        <div style={{ position: "absolute" }}>
          <HashLoader color="#004987" size="100" />
        </div>
      )}
    </>
  )
}
